### ISSUE TITLE
Segfault no renderer playback

### ISSUE THREAD

**Issue by cls-nebadje** [medoc92/upplay#36]
```
uli@ankerklause:~$ upplay -v
Upplay 1.2.4 libupnpp 0.14.1 libupnp 1.6.17
uli@ankerklause:~$ uname -a
Linux ankerklause 3.16.0-62-generic #83~14.04.1-Ubuntu SMP Fri Feb 26 22:52:48 UTC 2016 i686 i686 i686 GNU/Linux
```

 1. kill/terminate DMR during playback
 2. dialog "Connection to current rendererer lost. Choose again?": Cancel
 3. restart DMR
 4. double click playlist entry for playback

I use the ppa release. I haven't found any debug symbol file nor have the binaries included any (point me to them if there should be some). Therefore you have to live with this sparse backtrace for now.

```
#0  0xb7f7e804 in UPnPClient::Service::getServiceType() const () from /usr/lib/libupnpp.so.2
#1  0xb7f2506e in UPnPClient::AVTransport::setURI(std::string const&, std::string const&, int, bool) () from /usr/lib/libupnpp.so.2
#2  0x080c62f4 in ?? ()
#3  0x080dcd91 in ?? ()
#4  0xb50630f7 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#5  0x080d6d47 in ?? ()
#6  0x080d6fc9 in ?? ()
#7  0xb50630f7 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#8  0x080d7f67 in ?? ()
#9  0x080d7b5f in ?? ()
#10 0xb50630f7 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#11 0xb59c7085 in QAbstractItemView::doubleClicked(QModelIndex const&) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#12 0xb59d14f1 in QAbstractItemView::mouseDoubleClickEvent(QMouseEvent*) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#13 0xb549756b in QWidget::event(QEvent*) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#14 0xb589d91c in QFrame::event(QEvent*) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#15 0xb592bfd8 in QAbstractScrollArea::viewportEvent(QEvent*) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#16 0xb59d0f6c in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#17 0xb592c256 in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#18 0xb504dfbe in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#19 0xb543d7d1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#20 0xb5445ea0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#21 0xb504de4a in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#22 0xb5443b53 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/i386-linux-gnu/libQtGui.so.4
#23 0xb54c77a8 in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#24 0xb54c6ef5 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#25 0xb54f2554 in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#26 0xb454e1e3 in g_main_context_dispatch () from /lib/i386-linux-gnu/libglib-2.0.so.0
#27 0xb454e468 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#28 0xb454e528 in g_main_context_iteration () from /lib/i386-linux-gnu/libglib-2.0.so.0
#29 0xb507d93b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#30 0xb54f260e in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#31 0xb504c823 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
```

**Comment by cls-nebadje** [comment]
Here's the output of the log.
```
libupnpp/control/service.cxx:351::Service:unSubscribe: failed: -204 : UPNP_E_SOCKET_CONNECT
libupnpp/control/service.cxx:351::Service:unSubscribe: failed: -109 : UPNP_E_INVALID_SID
libupnpp/control/service.cxx:351::Service:unSubscribe: failed: -204 : UPNP_E_SOCKET_CONNECT
getDevByFname failed
Renderer uuid:Weiss-DAC501-1_0-000-000-002 not found
PlaylistAVT::set_for_playing  6 
AVT:changeTrack:  http://192.168.1.49:49153/content/media/object_id/7814/res_id/0/ext/file.mp3 

Program received signal SIGSEGV, Segmentation fault.
0xb4e9b92f in std::string::assign(std::string const&) () from /usr/lib/i386-linux-gnu/libstdc++.so.6
```

**Comment by medoc92** [comment]
Thanks for reporting this. It should be easy enough to reproduce even without a stack trace, I'll take a look next week.

**Comment by cls-nebadje** [comment]
Great. I'll probably report further issues. We're currently using upplay for testing a DMR implementation. So your code will profit from it as well ;)
Regards
Uli

**Comment by medoc92** [comment]
This  should hopefully be fixed in the latest git code. The playlist is now cleared when connection is lost, so there is nothing left to click on to crash the program :)
